SHOW CON_NAME;

ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER C##PROJECT IDENTIFIED BY strongpassword;
GRANT ALL PRIVILEGES TO C##PROJECT;

CREATE USER DBMS_PROJECT IDENTIFIED BY DBMS1234;
GRANT DBA TO DBMS_PROJECT;

-- ACCOUNT UNLOCK
-- DEFAULT TABLESPACE users
-- TEMPORARY TABLESPACE temp
-- QUOTA UNLIMITED ON users;


GRANT
  CREATE SESSION,
  CREATE TABLE,
  CREATE VIEW,
  CREATE SEQUENCE,
  CREATE PROCEDURE,
  CREATE TRIGGER
TO DBMS_PROJECT;
