 SELECT 
    *
 FROM 
    EMPLOYEES e 
JOIN 
    DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID 
JOIN 
    JOBS j ON e.JOB_ID = j.JOB_ID 
 WHERE UPPER(j.JOB_TITLE) LIKE 'S%' 
 ORDER BY d.DEPARTMENT_NAME;