SELECT 
    d.DEPARTMENT_NAME AS "Department Name", 
    AVG(e.SALARY) AS "Average Salary"
FROM 
    EMPLOYEES e
INNER JOIN 
    DEPARTMENTS d 
    ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
WHERE 
    UPPER(d.DEPARTMENT_NAME) = 'MARKETING'
GROUP BY 
    d.DEPARTMENT_NAME;
